# Generated by Django 4.2.5 on 2024-03-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('paystack', 'Paystack')], max_length=20, null=True, verbose_name='Payment method')),
                ('transaction_reason', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Reason')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Actual Amount')),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Transaction Fee')),
                ('flag', models.CharField(blank=True, choices=[('reversed', 'Reversed'), ('on-hold', 'On Hold')], max_length=25, null=True, verbose_name='Flag')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount in Naira')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Payment Reference Number')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paystack Fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack', to='payments.paymenttransaction')),
            ],
        ),
    ]
