# Generated by Django 4.2.5 on 2024-02-20 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, choices=[('poll', 'poll'), ('ticket', 'ticket'), ('live', 'live'), ('feed', 'feed'), ('connect', 'connect'), ('commerce', 'commerce'), ('business', 'business'), ('stereo', 'stereo'), ('ticket', 'ticket'), ('tv', 'tv')], max_length=500)),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('previous_balance', models.IntegerField(default=0)),
                ('after_balance', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ident', models.CharField(default=payments.models.create_id, editable=False, max_length=30)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS WALLET SUMMARY',
            },
        ),
        migrations.CreateModel(
            name='Wallet_Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, editable=False, max_length=500)),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('previous_balance', models.IntegerField(default=0, editable=False)),
                ('after_balance', models.IntegerField(default=0, editable=False, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('track_id', models.CharField(default=payments.models.create_id, editable=False, max_length=30)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_funding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
