# Generated by Django 4.2.5 on 2024-03-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='profile',
            new_name='user',
        ),
    ]
