# Generated by Django 4.2 on 2024-03-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=20, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
        migrations.CreateModel(
            name='UserCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover-files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='User Bio')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=15, null=True, verbose_name='Gender')),
                ('religion', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Muslim', 'Muslim'), ('Indigenous', 'Indigenous'), ('Others', 'Others')], max_length=20, null=True, verbose_name='Religion')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover-images', verbose_name='Cover Image')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-images', verbose_name='Profile Image')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Is flagged')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('stickers', models.ManyToManyField(blank=True, to='account.userprofile', verbose_name='Sticker')),
                ('sticking', models.ManyToManyField(blank=True, to='account.userprofile', verbose_name='Sticking')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='profile-files/')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('voice_note', 'voice_note'), ('music', 'music'), ('file', 'file')], max_length=20, null=True, verbose_name='Type of media')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile', verbose_name='Profile')),
            ],
        ),
    ]
