# Generated by Django 4.2.5 on 2024-03-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_blockedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUsers',
        ),
    ]
