# Generated by Django 4.2 on 2024-03-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='UserReward',
        ),
    ]
