# Generated by Django 4.2 on 2024-03-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_reward_userreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=20, verbose_name='Phone Name')),
                ('category', models.CharField(blank=True, choices=[('imei', 'imei'), ('serial_number', 'serial_number')], max_length=20, null=True, verbose_name='Category')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI/SerialNo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
