# Generated by Django 4.2.5 on 2024-03-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_blockedusers'),
        ('account', '0006_userphone'),
    ]

    operations = [
    ]
