# Generated by Django 4.2.5 on 2024-02-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_coverimagemedia_alter_userprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Artist Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('stickers', models.PositiveIntegerField(default=0, verbose_name='Stickers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='User Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='User Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SongCategories',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Song Title')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Duration')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song-cover-images', verbose_name='Cover Image')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs', verbose_name='Song File')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stereo.artist', verbose_name='Artist')),
                ('category', models.ManyToManyField(to='stereo.songcategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Search Keyword')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'verbose_name': 'SearchSong',
                'verbose_name_plural': 'SearchSongs',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist-cover-images', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stereo.library', verbose_name='Library')),
                ('songs', models.ManyToManyField(to='stereo.song', verbose_name='Songs')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album-cover-images', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stereo.artist')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stereo.library', verbose_name='Library')),
                ('songs', models.ManyToManyField(to='stereo.song', verbose_name='Songs')),
            ],
        ),
    ]
