# Generated by Django 4.2.5 on 2024-02-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coverimagemedia_alter_userprofile_cover_image'),
        ('stereo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Search Keyword')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
