# Generated by Django 4.2.5 on 2024-03-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('stereo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloads',
            field=models.ManyToManyField(related_name='downloads', to='user.userprofile', verbose_name='Downloads'),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='user.userprofile', verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.ManyToManyField(related_name='plays', to='user.userprofile', verbose_name='Plays'),
        ),
        migrations.AddField(
            model_name='searchsong',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stereo.library', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='stereo.song', verbose_name='Songs'),
        ),
        migrations.AddField(
            model_name='library',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='user.userprofile', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stereo.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stereo.library', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='stereo.song', verbose_name='Songs'),
        ),
    ]
