# Generated by Django 4.2.5 on 2024-02-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereo', '0002_searchsong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchsong',
            options={'verbose_name': 'SearchSong', 'verbose_name_plural': 'SearchSongs'},
        ),
    ]
