# Generated by Django 4.2.5 on 2024-02-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coverimagemedia_alter_userprofile_cover_image'),
        ('stereo', '0003_alter_searchsong_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.CharField(verbose_name='Full Name'),
        ),
        migrations.CreateModel(
            name='StereoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stereo_account', to='user.userprofile', verbose_name='User Profile')),
            ],
        ),
    ]
