# Generated by Django 4.2.5 on 2024-02-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereo', '0004_alter_artist_full_name_stereoaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
