# Generated by Django 4.2.5 on 2024-02-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coverimagemedia_alter_userprofile_cover_image'),
        ('stereo', '0005_remove_song_is_downloaded_remove_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='full_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artist Name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='User Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StereoAccount',
        ),
    ]
