# Generated by Django 4.2.5 on 2024-02-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('stereo', '0006_remove_artist_full_name_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='stickers',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='artist',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Brand Image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='user.userprofile', verbose_name='User Profile'),
        ),
    ]
