# Generated by Django 4.2.5 on 2024-02-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereo', '0007_remove_artist_picture_remove_artist_stickers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='download_count',
        ),
    ]
