# Generated by Django 4.2.5 on 2024-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('stereo', '0008_remove_song_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloads',
            field=models.ManyToManyField(related_name='downloads', to='user.userprofile', verbose_name='Downloads'),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='user.userprofile', verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.ManyToManyField(related_name='plays', to='user.userprofile', verbose_name='Plays'),
        ),
    ]
