# Generated by Django 4.2.5 on 2024-02-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessaccount_businessaddress_businesscategory_and_more'),
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount'),
        ),
    ]
