# Generated by Django 4.2.5 on 2024-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='angry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='love_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='sad_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
