# Generated by Django 4.2.5 on 2024-03-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_reply_angry_count_reply_dislike_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
