# Generated by Django 4.2.5 on 2024-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_reportpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='post_files', to='feeds.postfile'),
        ),
    ]
