# Generated by Django 4.2.5 on 2024-03-07 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0004_remove_post_file_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='file',
            field=models.FileField(blank=True, upload_to='status_files/'),
        ),
        migrations.AddField(
            model_name='status',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_in_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
