# Generated by Django 4.2.5 on 2024-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[(1, 'Like'), (2, 'Dislike'), (3, 'Love'), (4, 'Sad'), (5, 'Angry')], max_length=10),
        ),
    ]
