# Generated by Django 4.2.5 on 2024-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_status_caption_status_created_at_status_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='caption',
            field=models.TextField(),
        ),
    ]
