# Generated by Django 4.2.5 on 2024-03-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, verbose_name='Business Name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('business_image', models.ImageField(blank=True, null=True, upload_to='business-images/', verbose_name='Business Image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover-images/', verbose_name='Cover Image')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Email')),
                ('website_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('founded_on', models.DateField(blank=True, null=True, verbose_name='Founded On')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID')),
                ('document_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Type')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='business-files/', verbose_name='Document File')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identification Document Type')),
                ('id_document_file', models.FileField(blank=True, null=True, upload_to='business-owner-docs', verbose_name='Identification Document Type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_from', models.TimeField(verbose_name='Open')),
                ('close_at', models.TimeField(verbose_name='Close')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 3')),
                ('phone4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 4')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Name')),
                ('work', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work or Profession')),
                ('link1', models.URLField(blank=True, null=True, verbose_name='Link1')),
                ('link2', models.URLField(blank=True, null=True, verbose_name='Link2')),
                ('link3', models.URLField(blank=True, null=True, verbose_name='Link3')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Government issued ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business')),
            ],
        ),
    ]
