# Generated by Django 4.2.5 on 2024-03-05 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='user.userprofile', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='business.businesstimeavailability', verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='business.businesstimeavailability', verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='business.businesstimeavailability', verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='sunday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='business.businesstimeavailability', verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='business.businesstimeavailability', verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='business.businesstimeavailability', verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='business.businesstimeavailability', verbose_name='Wednesday'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='business.businesscategory', verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auth User'),
        ),
    ]
