# Generated by Django 4.2 on 2024-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='business_type',
            field=models.CharField(blank=True, choices=[('personal', 'personal'), ('company', 'company')], max_length=50, null=True, verbose_name='Business Type'),
        ),
    ]
