# Generated by Django 4.2 on 2024-03-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessaccount_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdocument',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessownerprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='about',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='business_image',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='business_type',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='business-pictures/', verbose_name='Business Display Picture'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='category',
            field=models.CharField(blank=True, choices=[('personal', 'personal'), ('company', 'company')], max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='businessverification',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='business-verify-images', verbose_name='Government issued ID'),
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
        migrations.DeleteModel(
            name='BusinessDocument',
        ),
        migrations.DeleteModel(
            name='BusinessOwnerProfile',
        ),
    ]
