# Generated by Django 4.2 on 2024-03-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_businessdocument_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='business_email',
        ),
    ]
