# Generated by Django 4.2 on 2024-03-10 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_businessaccount_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='office_phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None, verbose_name='Office phone number'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
