# Generated by Django 4.2.5 on 2024-02-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('business', '0004_businesscategory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerprofile',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='user.userprofile', verbose_name='User Profile'),
        ),
    ]
