# Generated by Django 4.2.5 on 2024-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessownerprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
    ]
