# Generated by Django 4.2 on 2024-03-10 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessaccount_office_phone_delete_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='office_phone',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='biz_phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None, verbose_name='Business phone numbers'),
        ),
    ]
