# Generated by Django 4.2.5 on 2024-02-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_businessaccount_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='category',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='categories',
            field=models.ManyToManyField(to='business.businesscategory', verbose_name='Business Category'),
        ),
    ]
