# Generated by Django 4.2 on 2024-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_businessaccount_office_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Email'),
        ),
    ]
