# Generated by Django 4.2 on 2024-03-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessaccount_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='business_email',
        ),
    ]
