# Generated by Django 4.2.5 on 2024-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_businessaccount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='categories',
            field=models.ManyToManyField(related_name='business_accounts', to='business.businesscategory', verbose_name='Business Category'),
        ),
    ]
