# Generated by Django 4.2.5 on 2024-02-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_businessaccount_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='business',
            field=models.ForeignKey(default='2342342342', on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 1'),
        ),
    ]
