# Generated by Django 4.2 on 2024-03-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userphone'),
        ('business', '0008_remove_businessaccount_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile', verbose_name='Profile'),
        ),
    ]
