# Generated by Django 4.2.5 on 2024-02-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_alter_businessownerprofile_id_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, verbose_name='Day')),
                ('open_from', models.TimeField(verbose_name='Open')),
                ('close_at', models.TimeField(verbose_name='Close')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Name')),
                ('work', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work or Profession')),
                ('link1', models.URLField(blank=True, null=True, verbose_name='Link1')),
                ('link2', models.URLField(blank=True, null=True, verbose_name='Link2')),
                ('link3', models.URLField(blank=True, null=True, verbose_name='Link3')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Government issued ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='businessdocument',
            options={'verbose_name': 'Business Address', 'verbose_name_plural': 'Business Addresses'},
        ),
        migrations.RenameField(
            model_name='businessaccount',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='businessaccount',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='businessaccount',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='businessaccount',
            old_name='website',
            new_name='website_link',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='image',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='role',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='business-images/', verbose_name='Business Image'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auth User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='business_name',
            field=models.CharField(max_length=50, verbose_name='Business Name'),
        ),
        migrations.DeleteModel(
            name='BusinessAddress',
        ),
        migrations.AddField(
            model_name='businessverification',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessavailability', verbose_name='Business Availability'),
        ),
    ]
