# Generated by Django 4.2.5 on 2024-02-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessavailability_businessverification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='businessdocument',
            name='profile',
        ),
        migrations.AddField(
            model_name='businessavailability',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='categories',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_accounts', to='business.businesscategory', verbose_name='Business Category'),
        ),
    ]
