# Generated by Django 4.2.5 on 2024-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_businessdocument_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='categories',
            new_name='category',
        ),
    ]
