# Generated by Django 4.2.5 on 2024-02-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_rename_categories_businessaccount_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessaccount', verbose_name='Business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_from', models.TimeField(verbose_name='Open')),
                ('close_at', models.TimeField(verbose_name='Close')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessAvailability',
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='business.businesstimeavailability', verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='business.businesstimeavailability', verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='business.businesstimeavailability', verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='sunday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='business.businesstimeavailability', verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='business.businesstimeavailability', verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='business.businesstimeavailability', verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='businessdayavailability',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='business.businesstimeavailability', verbose_name='Wednesday'),
        ),
    ]
