# Generated by Django 4.2.5 on 2024-02-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_businessdayavailability_businesstimeavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='business.businesscategory', verbose_name='Business Category'),
        ),
    ]
