# Generated by Django 4.2.5 on 2024-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_postmedia_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='media_type',
            field=models.CharField(blank=True, choices=[('Images', 'Images'), ('Videos', 'Videos'), ('Music', 'Music'), ('Location', 'Location'), ('Recording', 'Recording'), ('PDF', 'PDF'), ('Word', 'Word'), ('Excel', 'Excel'), ('PPT', 'PPT'), ('Files', 'Files'), ('Apk', 'Apk'), ('EXE', 'EXE')], max_length=256, null=True),
        ),
    ]
