# Generated by Django 4.2.5 on 2024-02-20 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=1, verbose_name='current bonus')),
                ('prev_bonus', models.IntegerField(blank=True, null=True, verbose_name='previous bonus')),
                ('medium', models.CharField(choices=[('login', 'login'), ('post_creation', 'post_creation'), ('comments', 'comments'), ('stick', 'stick'), ('likes', 'likes'), ('stickers', 'stickers'), ('time_rewards', 'time_rewards'), ('commerce', 'commerce'), ('start_livestream', 'start_livestream'), ('engage_livestream', 'engage_livestream'), ('buy_tickets', 'buy_tickets'), ('sell_tickets', 'sell_tickets'), ('stereo', 'stereo')], default='login', max_length=50, verbose_name='medium of earning')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Each User')),
            ],
        ),
        migrations.CreateModel(
            name='Claim_Reward_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims', models.IntegerField(default=0, verbose_name='total claims')),
                ('total_claims', models.IntegerField(default=0, verbose_name='total claims')),
                ('medium', models.CharField(max_length=256, verbose_name='medium')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='each_user')),
            ],
        ),
    ]
