# Generated by Django 4.2.5 on 2024-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stickers',
            field=models.ManyToManyField(blank=True, to='user.userprofile', verbose_name='Sticker'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sticking',
            field=models.ManyToManyField(blank=True, to='user.userprofile', verbose_name='Sticking'),
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
