# Generated by Django 4.2.5 on 2024-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_otp_remove_user_otp_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='verification_type',
            field=models.CharField(choices=[('account_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=25, verbose_name='Verification Type'),
        ),
    ]
