# Generated by Django 4.2.5 on 2024-02-21 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_address_apartment_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_categories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_updated_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='searched_polls',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stickers',
        ),
        migrations.AddField(
            model_name='profilemedia',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type of media'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TimeField(blank=True, null=True, verbose_name='User Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Is flagged'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Muslim', 'Muslim'), ('Indigenous', 'Indigenous'), ('Others', 'Others')], max_length=20, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Work'),
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticked_on', models.DateTimeField(auto_now_add=True)),
                ('sticked', models.ForeignKey(help_text='sticking are like those the user is following', on_delete=django.db.models.deletion.CASCADE, related_name='sticking', to='user.userprofile', verbose_name='Sticked')),
                ('sticker', models.ForeignKey(help_text='stickers are like a followers', on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='user.userprofile', verbose_name='Sticker')),
            ],
        ),
    ]
