# Generated by Django 4.2.5 on 2024-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images', verbose_name='Profile Image'),
        ),
        migrations.AlterUniqueTogether(
            name='sticker',
            unique_together={('sticker', 'sticked')},
        ),
    ]
