# Generated by Django 4.2.5 on 2024-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_product_business'),
        ('user', '0012_remove_userprofile_work_userprofile_occupation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.DeleteModel(
            name='BusinessAccount',
        ),
        migrations.DeleteModel(
            name='BusinessAvailability',
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
    ]
