# Generated by Django 4.2.5 on 2024-02-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
