# Generated by Django 4.2.5 on 2023-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_previous_balance_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoverimage',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_image/'),
        ),
    ]
