# Generated by Django 4.2.5 on 2024-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_usercoverimage_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(null=True),
        ),
    ]
