# Generated by Django 4.2.5 on 2024-01-27 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='user.businesscategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stickers',
            field=models.ManyToManyField(related_name='sticking', to=settings.AUTH_USER_MODEL),
        ),
    ]
