# Generated by Django 4.2.5 on 2024-02-20 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.Customstorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='cover-images/')),
                ('audio_file', models.FileField(storage=utils.Customstorage.CustomS3Boto3Storage(), upload_to='songs/')),
            ],
        ),
        migrations.CreateModel(
            name='Demovideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(default='default-audio.png', upload_to='cover-images/')),
                ('video_file', models.FileField(storage=utils.Customstorage.CustomS3Boto3Storage(), upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='Geopraphical_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='')),
                ('platform', models.CharField(max_length=50, null=True, verbose_name='')),
                ('websiteurl', models.CharField(max_length=50, null=True, verbose_name='')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='')),
                ('ticket_name', models.CharField(max_length=50, null=True, verbose_name='')),
                ('category', models.CharField(max_length=50, null=True, verbose_name='')),
                ('fee_settings_category', models.CharField(max_length=50, null=True, verbose_name='')),
                ('quantity', models.CharField(max_length=50, null=True, verbose_name='')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='')),
                ('IsPrivate', models.CharField(max_length=50, null=True, verbose_name='')),
                ('IsPublic', models.CharField(max_length=50, null=True, verbose_name='')),
                ('show_remaining_ticket', models.CharField(max_length=50, null=True, verbose_name='')),
                ('X_File', models.FileField(null=True, upload_to='loacation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
