# Generated by Django 4.2 on 2024-03-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=225, verbose_name='Question')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount')),
                ('poll_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Poll Type')),
                ('poll_access', models.CharField(blank=True, max_length=50, null=True, verbose_name='Poll Access')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='Close Time')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='poll-media-files', verbose_name='Media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile', verbose_name='Creator')),
                ('voters', models.ManyToManyField(blank=True, related_name='poll_voters', to='account.userprofile', verbose_name='Voters')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=225, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll.poll', verbose_name='Poll')),
                ('voters', models.ManyToManyField(blank=True, related_name='voters', to='account.userprofile', verbose_name='Voters')),
            ],
        ),
    ]
