# Generated by Django 4.2.5 on 2024-03-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to='user.userprofile', verbose_name='Voters'),
        ),
        migrations.AddField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile', verbose_name='Creator'),
        ),
    ]
