# Generated by Django 4.2.5 on 2024-02-24 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pollview',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='access_requests',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_ended',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='type',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.poll', verbose_name='Poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='option',
            name='voters',
            field=models.ManyToManyField(to='user.userprofile', verbose_name='Voters'),
        ),
        migrations.AddField(
            model_name='poll',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_access',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poll Access'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poll Type'),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.CharField(max_length=225, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='poll-media-files', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=225, verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PollMedia',
        ),
        migrations.DeleteModel(
            name='PollView',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
