# Generated by Django 4.2.5 on 2024-02-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('poll', '0003_alter_pollview_unique_together_remove_pollview_poll_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='PollOption',
        ),
    ]
