# Generated by Django 4.2.5 on 2024-02-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_address_useraddress_alter_user_phone_number_and_more'),
        ('poll', '0007_alter_polloption_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll.poll', verbose_name='Poll'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='voters',
            field=models.ManyToManyField(blank=True, to='user.userprofile', verbose_name='Voters'),
        ),
    ]
