# Generated by Django 4.2.5 on 2024-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_polloption_poll_alter_polloption_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='media',
            new_name='media_file',
        ),
    ]
