# Generated by Django 4.2.5 on 2024-02-24 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_alter_polloption_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
