# Generated by Django 4.2.5 on 2023-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_alter_poll_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
