# Generated by Django 4.2.5 on 2024-02-20 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'get_latest_by': 'time_stamp'},
        ),
        migrations.AddField(
            model_name='event',
            name='add_to_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='each_ticket',
            field=models.ManyToManyField(to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='20 Feb, 2024'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ed27994e-2f0a-4348-8fe5-a3750af3ebfe')),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_ticket', to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='payoutinfo',
            name='account_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payoutinfo',
            name='account_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payoutinfo',
            name='account_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='payoutinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='NGN', max_length=50)),
                ('balance', models.FloatField(default=0)),
                ('prev_balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fund', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Sales_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256, null=True)),
                ('platform', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('ticket', models.CharField(max_length=256, null=True)),
                ('ticket_key', models.CharField(max_length=256, null=True)),
                ('ticket_category', models.CharField(max_length=256, null=True)),
                ('ticket_price', models.CharField(max_length=256, null=True)),
                ('ticket_quantity', models.CharField(max_length=256, null=True)),
                ('ticket_ticket_key', models.CharField(max_length=256, null=True)),
                ('event_key', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('total_amount', models.FloatField(default=0)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_initiated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('payment_id', models.UUIDField(default=uuid.UUID('5ad48e22-94a3-4ddf-b81c-1cd177ee344b'))),
                ('ticket_quantity', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'time_stamp',
            },
        ),
        migrations.CreateModel(
            name='Ticket_Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('error_key', models.UUIDField(default=uuid.UUID('3cc870f3-3302-442d-a0f6-069fd6de508b'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Get_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=256)),
                ('ticket_type', models.CharField(choices=[('FREE TICKET', 'FREE TICKET'), ('PAID TICKET', 'PAID TICKET')], default='FREE TICKET', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='NGN', max_length=50)),
                ('balance', models.FloatField(default=0)),
                ('prev_balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_status', models.CharField(choices=[('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='FAILED')),
                ('transaction_id', models.CharField(max_length=256, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.event')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sales',
            field=models.ManyToManyField(to='ticket.ticket_payment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_sales',
            field=models.ManyToManyField(to='ticket.get_ticket'),
        ),
    ]
