# Generated by Django 4.2.5 on 2024-02-20 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_withdraw_options_event_add_to_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d7dcdd4f-f613-4f7a-88e5-31200fedf94e')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('d0536985-57de-4168-aa01-f993175ab1d8')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('0db03e40-4612-4d09-9e81-137276261a61')),
        ),
    ]
