# Generated by Django 4.2.5 on 2024-02-20 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('36bf5ded-fe25-4ab8-980d-9393705a9f5f')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('5c97bf87-d8dd-49dc-871e-90fb5e161eff')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('883db45a-5d5a-4a06-a81d-4bb684ce5dbb')),
        ),
    ]
