# Generated by Django 4.2.5 on 2024-02-20 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('e4f24661-4b14-4bf1-a360-f1a62c402f9b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('b5e265fa-74c9-40e6-8015-d80a4f8dfd88')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('884bdc21-50d8-4308-99c4-79c253a780d0')),
        ),
    ]
