# Generated by Django 4.2.5 on 2024-02-21 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('424573a2-73a4-4b99-97dd-a2ed42a75e87')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('5b45d768-5b3d-47c3-9e75-363e481451fc')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('87cd9766-1c0b-498b-a86f-8cd59534ba85')),
        ),
    ]
