# Generated by Django 4.2.5 on 2024-02-21 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('10dc8a4b-98b7-4770-bf4f-233c89e1e10c')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('8aa6929a-98c6-46ab-9c19-9ff5d100dc6e')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('0547a098-eb4b-45e3-aa6b-d3e40ac095cb')),
        ),
    ]
