# Generated by Django 4.2.5 on 2024-02-21 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('afda8d16-908a-4a22-9038-9d29f34c2740')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('65497df4-e422-43d2-87c1-3e07eb29a6fd')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9ba6543b-88f2-42be-92ca-7db95ca8c4f3')),
        ),
    ]
