# Generated by Django 4.2.5 on 2024-02-21 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ebfd58fe-8c4d-4930-8712-b1dc34865054')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('8de510d5-6711-4d70-82b7-2fb261eed9e4')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('b23c16d5-d798-41f2-a8be-a53d4caf5a73')),
        ),
    ]
