# Generated by Django 4.2.5 on 2024-02-22 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='22 Feb, 2024'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('bb11c563-d770-43d1-b5a0-02eb023d1ff9')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('5f80b3cf-497d-42b9-b25b-eb449b736c40')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('284b78d8-fbb4-499b-9a27-6125adae56ae')),
        ),
    ]
