# Generated by Django 4.2.5 on 2024-02-22 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_event_formated_date_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8821be83-6d0e-4f5e-a581-c9e5f00ffd15')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e69c5b4c-b568-47d0-bb6d-9c0407db8582')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('50be12f7-66f6-4501-8e85-8c9f946cbc84')),
        ),
    ]
