# Generated by Django 4.2.5 on 2024-02-22 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('b236359a-449f-4c8c-8dc3-3a6322655be8')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('65309281-7fbd-44be-b66d-8a8b674f6039')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c7a6e4cc-fdc6-40ca-b3f8-3be2ac86a44c')),
        ),
    ]
