# Generated by Django 4.2.5 on 2024-02-22 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('054275c8-5877-4277-8623-f63ccc14d6bb')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('66068bdd-4f41-4c90-a50d-a2ea7a7591c9')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f006fdf0-a449-426c-9538-3c1e4c8cf3da')),
        ),
    ]
