# Generated by Django 4.2.5 on 2024-02-22 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('15b82dee-b112-4512-9a2f-e93e8d728d26')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('ef9583f7-7582-473c-a799-1e6f29c311cb')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1a63a086-f771-4910-80d7-dc5aa6b76bbb')),
        ),
    ]
