# Generated by Django 4.2.5 on 2024-02-23 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='23 Feb, 2024'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('f20ca502-79c6-48de-94fb-b93711895319')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('d7d4cb55-6e80-44d0-80d7-435cff69d328')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('09042edb-7e72-4b08-96b9-568691f0e27f')),
        ),
    ]
