# Generated by Django 4.2.5 on 2024-02-23 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d30c33a5-1d80-46cb-88b3-75902d6b0adb')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('1f29e9fe-0ed8-4ddc-a928-7e397b927e0a')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('11237467-d127-4fd1-a2b3-d6b1acaf812e')),
        ),
    ]
