# Generated by Django 4.2.5 on 2024-02-23 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('31a71ab8-8e55-4113-be31-4dd019ab0e34')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('a38165bf-dfbe-4164-92d3-d174ffa4b3fd')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('e52dec5a-9ef7-4ff2-bcf4-5ecb1804b0e5')),
        ),
    ]
