# Generated by Django 4.2.5 on 2024-02-24 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_alter_event_formated_date_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('2b1b5346-6d4f-40a9-b158-e5ff81a5841b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('26200ba8-2786-4da5-a0f8-ad132e483e42')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('e5890b42-72b4-4e65-93a3-6211b249dec2')),
        ),
    ]
