# Generated by Django 4.2.5 on 2024-02-24 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('5c00b00f-c550-4329-9122-db7228f88ee6')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('d1d75f32-ddb8-4456-991e-9f3cb71e50d0')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('ebb30cdd-d7b1-4230-8c28-be596dd9bfed')),
        ),
    ]
