# Generated by Django 4.2.5 on 2024-02-24 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('edf205b8-e82e-4ca4-b138-94196873e935')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('b2de88d3-d9b3-4735-a971-6565e3afb6e8')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1bb24475-a766-4af1-a0ed-fd7c2c6ead9a')),
        ),
    ]
