# Generated by Django 4.2.5 on 2024-02-24 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('12f9ea9e-31da-4692-a506-0f1703ceccfb')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('ef1c02d9-1a68-4ae0-b2d9-92e3d5e6daec')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1b800481-a196-4d66-ae3b-50703bd684a9')),
        ),
    ]
