# Generated by Django 4.2.5 on 2024-02-24 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('df7ff168-8870-4ecc-9aad-155e5c24cb5e')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('41b078db-020d-4488-852a-1baf57408f10')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('76f68d6d-3cdf-4f5a-81b1-0e2cd9ce67f3')),
        ),
    ]
