# Generated by Django 4.2.5 on 2024-02-24 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('428d24eb-73bd-491d-99c0-425150bfad20')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('51c1fb54-ecb0-4cf1-a02d-b06e6c484983')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('6ad691f5-fa97-4d21-8349-f649deee83aa')),
        ),
    ]
