# Generated by Django 4.2.5 on 2024-02-24 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8ba01a9c-6782-4d03-a52a-fe1d2ab1b8cd')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('2b5d87ea-a08a-441a-8713-e1783de0b088')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('96ba12c5-9fe5-45fb-8a86-ba6554436b04')),
        ),
    ]
