# Generated by Django 4.2.5 on 2024-02-24 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('c905c752-447a-4c37-9007-49c27d1b08fc')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('08227dac-c1b6-4d54-9bad-bdfc0f5e9102')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('0840b65d-ab6c-41ff-a4a9-581440773aac')),
        ),
    ]
