# Generated by Django 4.2.5 on 2024-02-24 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0040_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('3eece237-b32b-4ece-b18b-292ec563f1c2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e9891f01-77bc-42e2-b0ed-a7b1d5bdf50c')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f6361991-ee73-4afb-bda9-558126ba6ac4')),
        ),
    ]
