# Generated by Django 4.2.5 on 2024-02-24 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('a6fc5091-2ec3-4f40-8915-acd5b9e21e21')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('da394543-9675-48ff-b66c-9e38c0ef14ae')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('18be350f-88c3-4c00-a35a-b140853c8ad7')),
        ),
    ]
