# Generated by Django 4.2.5 on 2024-01-08 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0121_alter_event_formated_date_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='08 Jan, 2024'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('a24f66fb-e5ff-4cb3-b1a0-7e9e99afca52')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('c57ac4d6-ac61-4920-bf84-876d4976e208')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('a28f63b9-0e25-412f-a1de-0535af397c73')),
        ),
    ]
