# Generated by Django 4.2.5 on 2024-01-27 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0123_alter_event_formated_date_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d220d87d-11c6-466f-9762-d2f56f7068a6')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('0fa35600-368a-4635-9208-84948db92f03')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('ee23a351-8a2c-47cf-9172-212ee0c55d77')),
        ),
    ]
