# Generated by Django 4.2 on 2024-03-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Notification Content')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile', verbose_name='User Profile')),
            ],
        ),
    ]
