# Generated by Django 4.2 on 2024-03-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('create_poll', 'create_poll'), ('vote', 'vote')], max_length=50, null=True, verbose_name='Action'),
        ),
    ]
